name: Google JSON Style Serializer

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]

jobs:
    ci:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v2
            - name: Run CI
            - run: yarn
            - run: yarn lint
            - run: yarn coverage

